### PR TITLE
constructor fixes

### LINKED ISSUE #264: Investigate the constructor in modifier-2 and why this is not being called.

### PR DESCRIPTION
**Pull request by SwatiEY**
closes #264

### CODE REVIEW

File: src/codeGenerators/orchestration/files/toOrchestration.ts [hunk 1]
```diff
@@ -392,6 +393,16 @@ const prepareSetupScript = (file: localFile, node: any) => {
   file.file = file.file.replace(/CONSTRUCTOR_CALL/g, constructorCall);
 }
 
+const prepareStartupScript = (file: localFile, node: any) => {
+  let constructorCall = ``;
+  if (!node.functionNames.includes('cnstrctr')) {
+    return;
+  } else {
+
```
Comment (lydiagarms) [inline src/codeGenerators/orchestration/files/toOrchestration.ts:401]: This function doesn't seem to do anything other than line 397. Can it be removed and replaced with just let constructorCall = ``;?

File: src/codeGenerators/orchestration/files/toOrchestration.ts [hunk 2]
```diff
@@ -440,9 +449,13 @@ export default function fileGenerator(node: any) {
...
 
-      const readPath = path.resolve(fileURLToPath(import.meta.url), '../../../../../src/boilerplate/common/bin/setup');
-      const startupScript = { filepath: 'bin/setup', file: fs.readFileSync(readPath, 'utf8') };
+      let readPath = path.resolve(fileURLToPath(import.meta.url), '../../../../../src/boilerplate/common/bin/setup');
+      const setupScript = { filepath: 'bin/setup', file: fs.readFileSync(readPath, 'utf8') };
+      files.push(setupScript);
+      readPath = path.resolve(fileURLToPath(import.meta.url), '../../../../../src/boilerplate/common/bin/startup');
+      const startupScript = { filepath: 'bin/startup', file: fs.readFileSync(readPath, 'utf8') };
       files.push(startupScript);
+      console.log(files);
```
Comment (lydiagarms) [inline src/codeGenerators/orchestration/files/toOrchestration.ts:458]: Is this console.log for debugging purposes or intentional??

**Review by lydiagarms — APPROVED** [review]
