### PR TITLE
fix: avoid picking variables names as decorators

### LINKED ISSUE #66: Ensure that variables with names including secret, known, etc. aren't removed in removeDecorators
Somewhat naively, we search for the decorator keywords `secret`, `known`, `unknown`, and `reinitialisable` in the input contract. Then we remove them and compile the resulting Solidity.

The current method in `src/parse/removeDecorators` searches using a regex which does not exclude variable names e.g. `secretId` and `knownVar2` would be picked up as decorators, causing errors.

The solution could be to either improve the regex to pick up standalone decorators only and/or throw errors when users appear to be naming variables with a reserved decorator.

### PR DESCRIPTION
**Pull request by dwebchapey**
This fixes #66 .
Now , regex are picked up as decorators only if the whole string matches . Attaching a screenshot of the expected matches output.

Screenshot 2022-03-03 at 9 58 09 AM
 
To test , rename variables and/or methods in `/test` zol files to substring of decorators like `KnownID` or `secretvalue1`

### CODE REVIEW

File: src/parse/removeDecorators.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ import backtrace from '../error/backtrace.js';
 import logger from '../utils/logger.js';
 
 // regex: matches all cases of 'known' unless they are directly preceded by 'un'
```
Comment (MirandaWood) [inline src/parse/removeDecorators.ts:13]: This all works, could you please update the regex comment here? Something like `regex: matches decorators when standalone words`, thanks :)

Comment (dwebchapey) [reply src/parse/removeDecorators.ts]: Done . Thanks

**Review by SwatiEY — APPROVED** [review]

**Review by SwatiEY — APPROVED** [review]
